# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_building_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='owner',
            new_name='user',
        ),
    ]
